name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-clj:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: "Setup Java 17"
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@12.3
      with:
        lein: 2.12.0
        clj-kondo: 2026.04.15
    - name: Cache dependencies
      uses: actions/cache@v5.0.5
      with:
        path: ~/.m2/repository
        key: "m2-${{ hashFiles('project.clj') }}"
    - name: "Lint with clj-kondo"
      run: clj-kondo --lint src/marginalia test
    - name: Run tests
      run: lein test
